'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".search .search-box {\n  height: 30px;\n  width: 100%;\n  background: #fff;\n  display: flex;\n  border-radius: 7px;\n  padding: 0 10px;\n  border: 2px solid rgba(221, 221, 221, 0.8666666667);\n  align-items: center;\n}\n.search .search-box .search-input {\n  border: none;\n  height: 100%;\n  width: 90%;\n  outline: none;\n  margin-left: 10px;\n}\n\n.hidden-box {\n  display: none;\n}\n\n.show-box {\n  width: 100%;\n  min-height: 100px;\n  position: absolute;\n  background-color: #fff;\n  box-shadow: rgba(9, 30, 66, 0.25) 0px 4px 8px, rgba(9, 30, 66, 0.31) 0px 0px 1px;\n  margin-top: 5px;\n  border-radius: 3px;\n  z-index: 1;\n  padding: 10px 0;\n}\n.show-box .sort-box .sort-title {\n  color: rgba(32, 45, 64, 0.4784313725);\n  font-size: 12px;\n  padding-left: 10px;\n  height: 20px;\n  line-height: 20px;\n}\n.show-box .sort-box .item-box .item-one {\n  padding: 0 10px;\n  display: flex;\n  align-items: center;\n  height: 40px;\n  background-color: #f5f7fa;\n  margin-bottom: 10px;\n}\n.show-box .sort-box .item-box .item-one img {\n  width: 20px;\n  height: 20px;\n}\n.show-box .sort-box .item-box .item-one span {\n  width: 100px;\n  text-align: left;\n  margin-left: 20px;\n  overflow: hidden;\n}\n\n.search-resule .search-box {\n  height: 50px;\n  width: 100%;\n  background: #fff;\n  display: flex;\n  border-radius: 7px;\n  border: 2px solid rgba(221, 221, 221, 0.8666666667);\n  align-items: center;\n  justify-content: space-between;\n  margin: 20px 0;\n}\n.search-resule .search-box .search-input {\n  border: none;\n  height: 100%;\n  width: 90%;\n  outline: none;\n  margin-left: 10px;\n}\n.search-resule .search-box .search-botton {\n  width: 100px;\n  height: 100%;\n  line-height: 44px;\n  text-align: center;\n  background-color: powderblue;\n  color: #999;\n  font-weight: 600;\n  font-size: 18px;\n  cursor: pointer;\n}\n.search-resule .wiki-box .wiki-contant {\n  line-height: 30px;\n  border-bottom: 1px solid #f0f0f0;\n  padding-bottom: 10px;\n}\n.search-resule .wiki-box .wiki-contant .wiki-title {\n  color: #0053ca;\n  font-size: 18px;\n  font-weight: 600;\n}\n.search-resule .wiki-box .wiki-contant .wiki-item-name {\n  font-weight: 600;\n}\n.search-resule .wiki-box .wiki-card-item {\n  box-shadow: rgba(9, 30, 66, 0.25) 0px 1px 1px, rgba(9, 30, 66, 0.31) 0px 0px 1px;\n  width: 30%;\n  margin: 10px;\n  border-radius: 5px;\n  padding: 10px;\n  line-height: 30px;\n}\n.search-resule .wiki-box .wiki-card-item .wiki-card-contant {\n  display: flex;\n  justify-content: flex-start;\n  align-items: center;\n}\n.search-resule .wiki-box .wiki-card-item .wiki-card-contant img {\n  width: 36px;\n}\n.search-resule .wiki-box .wiki-card-item .wiki-card-contant .wiki-card-title {\n  color: #202d40;\n  font-weight: 600;\n}\n.search-resule .wiki-box .wiki-card-item .wiki-card-contant .wiki-card-item-name {\n  color: #d5d5d5;\n}\n.search-resule .wiki-box .wiki-card-item .wiki-card-bottom {\n  border-top: 1px solid #f0f0f0;\n  font-size: 12px;\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
