'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".document-examine .examine-title {\n  font-size: 18px;\n  font-weight: 600;\n  line-height: 30px;\n  height: 30px;\n  margin-bottom: 20px;\n}\n.document-examine .examine-type {\n  font-size: 12px;\n  color: #aaa;\n  margin-left: 20px;\n}\n.document-examine .preview-editor {\n  min-height: 300px;\n  box-shadow: rgb(179, 186, 197) 0px 0px 1px 0px, rgb(193, 199, 208) 0px 1px 1px 0px;\n}\n.document-examine .examine-comment {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  margin: 10px 0;\n}\n.document-examine .examine-comment .comment-item {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  margin-right: 10px;\n}\n.document-examine .examine-comment .comment-item .icon {\n  width: 20px;\n  height: 20px;\n}\n.document-examine .examine-comment .comment-item .number {\n  font-weight: 600;\n  font-size: 12px;\n}\n.document-examine .edit-comment {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n}\n.document-examine .edit-comment .user-icon {\n  width: 30px;\n  height: 30px;\n  border-radius: 15px;\n  margin-right: 15px;\n}\n.document-examine .edit-comment .ant-input {\n  border-radius: 15px;\n  margin-right: 10px;\n}\n.document-examine .comment-list {\n  margin: 20px 0;\n}\n.document-examine .comment-list .title {\n  font-size: 18px;\n  font-weight: 600;\n}\n.document-examine .comment-list .comment-user {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  margin: 20px 0;\n}\n.document-examine .comment-list .comment-user .user-icon {\n  width: 30px;\n  height: 30px;\n  border-radius: 15px;\n  margin-right: 10px;\n}\n.document-examine .comment-list .comment-user .user-name {\n  font-size: 14px;\n  font-weight: 600;\n  color: #0053ca;\n}\n.document-examine .comment-list .comment-content {\n  margin-left: 40px;\n  margin-bottom: 20px;\n}\n.document-examine .comment-list .comment-operate {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  margin-left: 40px;\n  font-size: 12px;\n  font-size: rgb(56, 55, 55);\n}\n.document-examine .comment-list .comment-operate span {\n  margin-right: 10px;\n}\n.document-examine .comment-list .edit-comment-show {\n  display: flex;\n  margin: 10px 0 10px 30px;\n}\n.document-examine .comment-list .edit-comment-hidden {\n  display: none;\n}\n.document-examine .comment-list .commnet-children-item {\n  margin-left: 30px;\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
