'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".wiki-set {\n  height: calc(100vh - var(--tiklab-head-height));\n}\n.wiki-set .ant-row {\n  overflow: auto;\n}\n.wiki-set .ant-layout {\n  background-color: #fff;\n}\n.wiki-set .ant-layout-sider {\n  background-color: var(--tiklab-gray-600);\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children {\n  position: fixed;\n  width: 200px;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside {\n  background: var(--tiklab-gray-600);\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside ul {\n  padding: 0;\n  margin: 0;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-set-title {\n  height: 40px;\n  display: flex;\n  line-height: 40px;\n  width: 100%;\n  align-items: center;\n  padding: 0 20px;\n  font-weight: 600;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-set-back {\n  height: 40px;\n  line-height: 40px;\n  padding-left: 20px;\n  border-bottom: 1px solid #f0f2f5;\n  align-items: center;\n  display: flex;\n  cursor: pointer;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-set-back:hover {\n  background-color: #e3e8f0;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .setting {\n  border-top: 1px solid #f0f2f5;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-menu {\n  list-style-type: none;\n  height: 85vh;\n  cursor: pointer;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-menu .wiki-menu-submenu {\n  height: 40px;\n  display: flex;\n  line-height: 40px;\n  width: 100%;\n  align-items: center;\n  padding-left: 20px;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-menu .wiki-menu-submenu i {\n  margin-right: 10px;\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-menu .wiki-menu-submenu:hover {\n  background-color: var(--tiklab-gray-300);\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .wiki-menu .wiki-menu-select {\n  background-color: var(--tiklab-gray-400);\n}\n.wiki-set .ant-layout-sider .ant-layout-sider-children .wiki-set-aside .hidden-menu {\n  display: none;\n}\n.wiki-set .wiki-set-content .wiki-set-content-col {\n  background: #fff;\n  height: 100%;\n}\n.wiki-set .wiki-back {\n  padding: 0 20px;\n  font-weight: 600;\n  color: var(--tiklab-blue);\n  cursor: pointer;\n  height: 40px;\n  line-height: 40px;\n}\n.wiki-set .wiki-back:hover {\n  background-color: #f0f2f5;\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
