'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".wiki-select-type {\n  padding: 10px 0;\n}\n.wiki-select-type .wiki-type-head {\n  font-size: 14px;\n  padding-bottom: 8px;\n  line-height: 30px;\n}\n.wiki-select-type .wiki-type-content {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  width: 60%;\n}\n.wiki-select-type .wiki-type-box {\n  display: flex;\n  justify-content: space-around;\n  align-items: center;\n  padding: 10 20px;\n  max-width: 300px;\n  background-color: #fff;\n}\n.wiki-select-type .wiki-type-box .type-info {\n  margin-left: 20px;\n}\n.wiki-select-type .wiki-type-box .type-info .type-name {\n  font-weight: bold;\n  height: 30px;\n  line-height: 30px;\n}\n.wiki-select-type .wiki-type-box .type-info .type-desc {\n  font-size: var(--tiklab-font-12);\n  color: var(--tiklab-gray-500);\n}\n\n.wiki-addinfo {\n  padding-top: 20px;\n}\n.wiki-addinfo .ant-form-item {\n  margin: 0 0 15px;\n}\n.wiki-addinfo .ant-input {\n  border: 0;\n}\n.wiki-addinfo .ant-picker {\n  border: 0;\n}\n.wiki-addinfo .wiki-icon-box {\n  width: 320px;\n  display: flex;\n  align-items: center;\n  flex-wrap: wrap;\n  gap: 10px;\n}\n.wiki-addinfo .wiki-icon-box .upload-icon {\n  width: 30px;\n  height: 30px;\n}\n.wiki-addinfo .wiki-limit {\n  display: flex;\n  align-items: center;\n  gap: 30px;\n}\n.wiki-addinfo .wiki-limit .wiki-limits {\n  padding: 15px 20px;\n  background-color: #fff;\n  border-radius: 4px;\n  width: 250px;\n}\n.wiki-addinfo .wiki-limit .wiki-limits .limits-title {\n  font-size: 16px;\n  height: 40px;\n  line-height: 40px;\n}\n.wiki-addinfo .wiki-limit .wiki-limits .limits-desc {\n  font-size: 13px;\n  color: #ccc;\n}\n.wiki-addinfo .wiki-limit .limit-select {\n  border: 1px solid var(--tiklab-blue);\n  box-shadow: 0 0 3px var(--tiklab-gray-400) 56;\n}\n.wiki-addinfo .wiki-type-head {\n  font-size: 20px;\n  font-weight: var(--tiklab-font-weight-bold);\n  margin-bottom: 10px;\n}\n.wiki-addinfo .wiki-icon {\n  box-sizing: content-box;\n  padding: 5px;\n}\n.wiki-addinfo .wiki-icon img {\n  width: 30px;\n  height: 30px;\n  margin: 0;\n}\n.wiki-addinfo .wiki-add-submit {\n  display: flex;\n  gap: 20px;\n}\n.wiki-addinfo .icon-select {\n  border: 1px solid var(--tiklab-blue);\n  box-shadow: 0 0 3px rgba(0, 99, 255, 0.337254902);\n  border-radius: 4px;\n}\n\n.wiki-previous {\n  line-height: 56px;\n  height: 56px;\n  display: flex;\n  align-items: center;\n  width: 56px;\n}\n\n.previous-icon {\n  width: 25px;\n  height: 25px;\n  cursor: pointer;\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
