'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".frame-header-drawer {\n  top: var(--tiklab-head-height);\n}\n.frame-header-drawer .ant-drawer-header {\n  padding: 9px 20px;\n  border-bottom: 0;\n}\n.frame-header-drawer .ant-drawer-close {\n  padding: 12px 20px;\n}\n.frame-header-drawer .ant-drawer-body {\n  padding: 0;\n  overflow: hidden;\n}\n.frame-header-drawer .ant-drawer-body .ant-tabs-nav {\n  padding: 0 20px;\n}\n.frame-header-drawer .message-box {\n  height: calc(100vh - 170px);\n  overflow: auto;\n  padding: 0 20px;\n}\n.frame-header-drawer .message-box .message-list {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding-bottom: 10px;\n  cursor: pointer;\n}\n.frame-header-drawer .message-box .message-list .message-status {\n  width: 6px;\n  height: 6px;\n  border-radius: 6px;\n  margin-left: 15px;\n}\n.frame-header-drawer .message-box .message-list .status-unread {\n  background: #ff0000;\n}\n.frame-header-drawer .message-box .message-list .status-read {\n  background-color: #00ff00;\n}\n.frame-header-drawer .message-box .message-item-text {\n  flex: 1;\n  margin-left: 10px;\n}\n.frame-header-drawer .message-box .message-item-text .message-item-title {\n  height: 40px;\n  line-height: 40px;\n  font-weight: var(--tiklab-font-weight-bold);\n  font-size: 16px;\n}\n.frame-header-drawer .message-box .message-item-text .message-item-title .message-item-time {\n  padding: 0 10px;\n  font-size: 12px;\n  color: #999;\n}\n.frame-header-drawer .message-box .message-item-text .message-item-desc {\n  height: 30px;\n  line-height: 30px;\n}\n.frame-header-drawer .message-box .message-item-id {\n  font-size: 12px;\n  color: #999;\n}\n.frame-header-drawer .message-box .message-list-bottom {\n  text-align: center;\n  font-size: 12px;\n  height: 30px;\n  line-height: 30px;\n  cursor: pointer;\n}\n.frame-header-drawer .message-box .message-list-bottom:hover {\n  color: var(--tiklab-blue);\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
