'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".comment {\n  display: block;\n  padding: 10px;\n  border-radius: 4px;\n  background: #fff;\n  box-shadow: 0 3px 6px -4px rgba(0, 0, 0, 0.1215686275), 0 6px 16px rgba(0, 0, 0, 0.0784313725), 0 9px 28px 8px rgba(0, 0, 0, 0.0509803922);\n  transition: all 5s linear;\n  height: calc(100vh - 100px);\n  overflow: auto;\n}\n\n.comment-top {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n.comment-top .comment-title {\n  font-size: 15px;\n  font-weight: 600;\n}\n\n.hidden-comment {\n  display: none;\n}\n\n.comment-list {\n  margin: 20px 0;\n  border-radius: 10px;\n}\n.comment-list .title {\n  font-size: 18px;\n  font-weight: 600;\n}\n.comment-list .edit-comment {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  margin: 10px 0;\n}\n.comment-list .edit-comment .user-icon {\n  width: 30px;\n  height: 30px;\n  border-radius: 15px;\n  margin-right: 15px;\n}\n.comment-list .edit-comment .ant-input {\n  border-radius: 15px;\n  margin-right: 10px;\n  border: 0;\n  flex: 1;\n  background: #f7f7f7;\n}\n.comment-list .comment-item .comment-user {\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  margin: 20px 0;\n}\n.comment-list .comment-item .comment-user .user-icon {\n  width: 30px;\n  height: 30px;\n  border-radius: 15px;\n  margin-right: 10px;\n}\n.comment-list .comment-item .comment-user .user-name {\n  font-size: 14px;\n  font-weight: 600;\n  color: #0053ca;\n}\n.comment-list .comment-item .comment-content {\n  margin-left: 40px;\n  margin-bottom: 20px;\n}\n.comment-list .comment-item .comment-operate {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  margin-left: 40px;\n  font-size: 12px;\n  color: #6b778c;\n}\n.comment-list .comment-item .comment-operate span {\n  margin-right: 10px;\n}\n.comment-list .comment-more-botton {\n  height: 40px;\n  line-height: 40px;\n  text-align: center;\n  cursor: pointer;\n  color: #0053ca;\n}\n.comment-list .edit-comment-show {\n  display: flex;\n  margin: 10px 0 10px 30px;\n}\n.comment-list .edit-comment-hidden {\n  display: none;\n}\n.comment-list .commnet-children-item {\n  margin-left: 30px;\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
