'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var styleInject_es = require('../../../../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".log-detail {\n  padding: 15px;\n  background-color: #fff;\n  height: 100%;\n}\n.log-detail-header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n.log-detail-button span {\n  cursor: pointer;\n  color: #0053ca;\n}\n.log-detail .log-edit .edit-toolbar {\n  padding: 0;\n  flex-wrap: nowrap;\n}\n.log-detail .log-edit .edit-title {\n  padding: 10px 0;\n  font-size: 16px;\n  font-weight: 600;\n}\n.log-detail .log-examine .examine-title {\n  font-size: 18px;\n  font-weight: 600;\n  line-height: 30px;\n  height: 30px;\n  margin-bottom: 20px;\n}\n.log-detail .log-examine .examine-type {\n  font-size: 12px;\n  color: #aaa;\n  margin-left: 20px;\n}\n.log-detail .log-title {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  border-bottom: 1px solid #f0f0f0;\n  padding-bottom: 10px;\n}\n.log-detail .log-title .title-icon {\n  width: 40px;\n  height: 40px;\n}\n.log-detail .log-title .title-left {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n}\n.log-detail .log-title .title-left .title-name {\n  margin-left: 20px;\n}\n.log-detail .log-title .title-left .title-name .name {\n  font-size: 18px;\n  font-weight: 600;\n}\n.log-detail .log-title .title-left .title-name .master {\n  color: var(--tiklab-gray-500);\n}\n.log-detail .log-title .top-add-botton {\n  color: #fff;\n  font-weight: 500;\n  background-color: var(--tiklab-blue);\n  padding: 5px 15px;\n  border-radius: 4px;\n  display: flex;\n  align-items: center;\n  cursor: pointer;\n  height: 32px;\n  line-height: 32px;\n}\n.log-detail .log-child {\n  border-bottom: 1px solid #f0f0f0;\n}\n.log-detail .log-child-list {\n  display: flex;\n  align-items: center;\n  height: 50px;\n  line-height: 50px;\n  justify-content: space-between;\n  padding: 0 10px;\n  border-radius: 4px;\n}\n.log-detail .log-child-list .log-child-name {\n  display: flex;\n  align-items: center;\n}\n.log-detail .log-child .log-child-list:hover {\n  background-color: var(--tiklab-gray-300);\n}\n.log-detail .log-child .log-icon {\n  width: 16px;\n  height: 16px;\n  margin-right: 5px;\n}";
styleInject_es["default"](css_248z);

exports["default"] = css_248z;
